# Netlify configuration for Nuxt 4 with Prisma + Supabase
[build]
  command = "npm run build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--legacy-peer-deps"
  # Prisma will use DATABASE_URL from environment variables
  # Note: DIRECT_URL is only needed for migrations, not for builds

[functions]
  directory = ".output/server"
  node_bundler = "esbuild"
  # Include Prisma client files in the function bundle
  included_files = [
    "node_modules/@prisma/client/**/*",
    "node_modules/.prisma/client/**/*",
    "node_modules/pg/**/*",
    "node_modules/@prisma/adapter-pg/**/*"
  ]
  # Increase function timeout for database operations
  [functions.server]
    timeout = 30

# Redirect all requests to Nuxt server function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = false

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache static assets
[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=86400"
